# Generated by Django 3.0.9 on 2020-08-03 21:47

from django.db import migrations, models
import webhunter.models


class Migration(migrations.Migration):

    dependencies = [
        ('webhunter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=webhunter.models.user_directory_path)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
